INSERT INTO amenities (id, type) VALUES (1, '와이파이');
INSERT INTO amenities (id, type) VALUES (2, '취식');
INSERT INTO amenities (id, type) VALUES (3, '냉장고');
INSERT INTO amenities (id, type) VALUES (4, '세탁기');
INSERT INTO amenities (id, type) VALUES (5, '건조기');
INSERT INTO amenities (id, type) VALUES (6, '에어컨');
INSERT INTO amenities (id, type) VALUES (7, '난방');
INSERT INTO amenities (id, type) VALUES (8, 'TV');
INSERT INTO amenities (id, type) VALUES (9, '세면용품');
INSERT INTO amenities (id, type) VALUES (10, '헤어드라이어');
INSERT INTO amenities (id, type) VALUES (11, '고데기');
INSERT INTO amenities (id, type) VALUES (12, '야외 수영장');
INSERT INTO amenities (id, type) VALUES (13, '자쿠지');
INSERT INTO amenities (id, type) VALUES (14, '대형 욕조');
INSERT INTO amenities (id, type) VALUES (15, '무료 주차');
INSERT INTO amenities (id, type) VALUES (16, '유료 주차');
INSERT INTO amenities (id, type) VALUES (17, '전기차 충전시설');
INSERT INTO amenities (id, type) VALUES (18, '바비큐');
INSERT INTO amenities (id, type) VALUES (19, '조식');
INSERT INTO amenities (id, type) VALUES (20, '픽업');
INSERT INTO amenities (id, type) VALUES (21, '짐 보관');

INSERT INTO tags (id, name, category) VALUES (1, '침대가 편안해요', 'INDOOR');
INSERT INTO tags (id, name, category) VALUES (2, '침구 상태가 좋아요', 'INDOOR');
INSERT INTO tags (id, name, category) VALUES (3, '조식이 맛있어요', 'INDOOR');
INSERT INTO tags (id, name, category) VALUES (4, '인테리어가 멋져요', 'INDOOR');
INSERT INTO tags (id, name, category) VALUES (5, '깨끗해요', 'INDOOR');
INSERT INTO tags (id, name, category) VALUES (6, '조용해요', 'AMBIENCE');
INSERT INTO tags (id, name, category) VALUES (7, '파티가 재미있어요', 'AMBIENCE');
INSERT INTO tags (id, name, category) VALUES (8, '바다가 잘 보여요', 'AMBIENCE');
INSERT INTO tags (id, name, category) VALUES (9, '뷰가 예뻐요', 'AMBIENCE');
INSERT INTO tags (id, name, category) VALUES (10, '사장님이 친절해요', 'HOST');
INSERT INTO tags (id, name, category) VALUES (11, '숙소까지 픽업을 해줘요', 'HOST');
INSERT INTO tags (id, name, category) VALUES (12, '짐 보관이 가능해요', 'OTHER');