INSERT INTO amenities (id, type) VALUES (1, '와이파이');
INSERT INTO amenities (id, type) VALUES (2, '취식');
INSERT INTO amenities (id, type) VALUES (3, '냉장고');
INSERT INTO amenities (id, type) VALUES (4, '세탁기');
INSERT INTO amenities (id, type) VALUES (5, '건조기');
INSERT INTO amenities (id, type) VALUES (6, '에어컨');
INSERT INTO amenities (id, type) VALUES (7, '난방');
INSERT INTO amenities (id, type) VALUES (8, 'TV');
INSERT INTO amenities (id, type) VALUES (9, '세면용품');
INSERT INTO amenities (id, type) VALUES (10, '헤어드라이어');
INSERT INTO amenities (id, type) VALUES (11, '고데기');
INSERT INTO amenities (id, type) VALUES (12, '야외 수영장');
INSERT INTO amenities (id, type) VALUES (13, '자쿠지');
INSERT INTO amenities (id, type) VALUES (14, '대형 욕조');
INSERT INTO amenities (id, type) VALUES (15, '무료 주차');
INSERT INTO amenities (id, type) VALUES (16, '유료 주차');
INSERT INTO amenities (id, type) VALUES (17, '전기차 충전시설');
INSERT INTO amenities (id, type) VALUES (18, '바비큐');
INSERT INTO amenities (id, type) VALUES (19, '조식');
INSERT INTO amenities (id, type) VALUES (20, '픽업');
INSERT INTO amenities (id, type) VALUES (21, '짐 보관');